spring:
  datasource:
    url: jdbc:h2:~/data/demo
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret: "12345678901234567890123456789010"
